language: rust
cache: cargo # cache dependencies to reduce compilation times
rust:
  - stable
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  # - cargo clippy -- -D warnings
  - cargo test
  - cargo test --features serde
  - cargo test --features decimal --tests
  - cargo package
