use std::fmt;

use crate::errors::{Result, TaError};
use crate::indicators::{RelativeStrengthIndex, SimpleMovingAverage, ExponentialMovingAverage};
use crate::{Close, Next, Period, Reset};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

/// Quantitative Qualitative Estimation (QQE).
/// 
/// An indicator similar to SuperTrend that uses a smoothed RSI as a base for 
/// two trailing (upper & lower) bands. The band width is derived from a true range of
/// the smoothed RSI base which is then doubly smoothed with a Wilder's Smoothing Function.
/// 
/// Trading signals are generated by a combination of crossovers of the three levels/lines.
///
/// # Example
///
/// ```
/// use ta::indicators::QuantitativeQualitativeEstimation;
/// use ta::Next;
///
/// let mut qqe = QuantitativeQualitativeEstimation::new(5, 5, 3.0).unwrap();
/// assert_eq!(qqe.next(10.0), 10.0); // TODO: Fix these at the same time as the tests.
/// assert_eq!(qqe.next(13.0), 14.0); // tomorrow morning ('21-08-07)
/// assert_eq!(qqe.next(16.0), 18.0);
/// assert_eq!(qqe.next(14.0), 13.5);
/// ```
///
/// # Links
///
/// * [Quantitative Qualitative Estimation, Tradingpedia](https://www.tradingpedia.com/forex-trading-indicators/quantitative-qualitative-estimation)
/// * [Pinescript Implementation, TradingView](https://www.tradingview.com/script/IYfA9R2k-QQE-MT4/)
///

#[doc(alias = "QQE")]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[derive(Debug, Clone)]
pub struct QuantitativeQualitativeEstimation {
    period: usize,
    wilders_multiplier: f64,
    rsi: RelativeStrengthIndex,
    // This should really be an option between different moving averages,
    // but I'm unsure on the best way to implement that. MA marker trait maybe?
    rsi_smoother: ExponentialMovingAverage,
    wilders_smoother: ExponentialMovingAverage,
}

#[derive(Debug, Clone, PartialEq)]
pub struct QuantitativeQualitativeEstimationOutput {
    pub rsi_ma: f64,
    pub qqe_short: f64,
    pub qqe_long: f64,
}


impl QuantitativeQualitativeEstimation {
    pub fn new(
        period: usize, 
        smooth_length: usize, 
        wilders_multiplier: f64,
    ) -> Result<Self> {
        if wilders_multiplier < 1.0 {
            Err(TaError::InvalidParameter)
        } else {
            let wilders_length = 2 * period - 1;
            Ok(Self {
                period,
                wilders_multiplier,
                rsi: RelativeStrengthIndex::new(period)?,
                rsi_smoother: ExponentialMovingAverage::new(smooth_length)?,
                wilders_smoother: ExponentialMovingAverage::new(wilders_length)?,
            })
        }
    }
}

impl Period for QuantitativeQualitativeEstimation {
    fn period(&self) -> usize {
        self.period
    }
}

impl Next<f64> for QuantitativeQualitativeEstimation {
    type Output = QuantitativeQualitativeEstimationOutput;

    fn next(&mut self, input: f64) -> Self::Output {
        
        Self::Output {
            rsi_ma: input.clone(),
            qqe_long: input.clone(),
            qqe_short: input.clone(),
        }
    }
}

impl<T: Close> Next<&T> for QuantitativeQualitativeEstimation {
    type Output = QuantitativeQualitativeEstimationOutput;

    fn next(&mut self, input: &T) -> Self::Output {
        self.next(input.close())
    }
}

impl Reset for QuantitativeQualitativeEstimation {
    fn reset(&mut self) {
        self.rsi.reset();
        self.rsi_smoother.reset();
        self.wilders_smoother.reset();
    }
}

impl Default for QuantitativeQualitativeEstimation {
    fn default() -> Self {
        Self::new(14, 5, 4.236).unwrap()
    }
}

impl fmt::Display for QuantitativeQualitativeEstimation {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "QQE({}, {}, {})", 
            self.period, 
            self.rsi_smoother.period(), 
            self.wilders_multiplier)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_helper::*;

    test_indicator!(QuantitativeQualitativeEstimation);

    #[test]
    fn test_new() {
        assert!(QuantitativeQualitativeEstimation::new(0, 5, 4.236).is_err());
        assert!(QuantitativeQualitativeEstimation::new(14, 0, 4.236).is_err());
        assert!(QuantitativeQualitativeEstimation::new(14, 5, 0.0).is_err());
        assert!(QuantitativeQualitativeEstimation::new(14, 5, 0.5).is_err());
        assert!(QuantitativeQualitativeEstimation::new(14, 5, -4.236).is_err());
        assert!(QuantitativeQualitativeEstimation::new(3, 3, 2.0).is_ok());
        assert!(QuantitativeQualitativeEstimation::new(14, 3, 5.45).is_ok());
    }

    #[test]
    fn test_next() {
        let mut qqe = QuantitativeQualitativeEstimation::default();

        // assert_eq!(round(qqe.next(12.0)), 12.0); // TODO: tomorrow morning
        // assert_eq!(round(qqe.next(9.0)), 8.0);
        // assert_eq!(round(qqe.next(7.0)), 5.5);
        // assert_eq!(round(qqe.next(13.0)), 15.667);

        let mut qqe = QuantitativeQualitativeEstimation::default();
        let bar1 = Bar::new().close(8);
        let bar2 = Bar::new().close(5);
        // assert_eq!(qqe.next(&bar1), 8.0);
        // assert_eq!(qqe.next(&bar2), 4.0);
    }

    #[test]
    fn test_reset() {
        let mut qqe = QuantitativeQualitativeEstimation::new(5, 5, 3.0).unwrap();

        // assert_eq!(qqe.next(4.0), 4.0);
        qqe.next(10.0);
        qqe.next(15.0);
        qqe.next(20.0);
        // assert_ne!(qqe.next(4.0), 4.0);

        qqe.reset();
        // assert_eq!(qqe.next(4.0), 4.0);
    }

    #[test]
    fn test_default() {
        QuantitativeQualitativeEstimation::default();
    }

    #[test]
    fn test_display() {
        let qqe = QuantitativeQualitativeEstimation::new(7, 3, 5.33).unwrap();
        assert_eq!(format!("{}", qqe), "QQE(7, 3, 5.33)");
    }
}
